Reclock audio input, when needed
mozilla/cubeb-coreaudio-rs pull request #153
Opened 2022-03-02 17:41 UTC by padenot

This won't compile until the changes are merged in https://github.com/mozilla/cubeb/pull/690 and https://github.com/mozilla/cubeb-rs/pull/62.

When using aggregate devices, macOS reclocks for us. When not using them, it may be that they are still in the same clock domain, in which case no reclocking is necessary. If that's not the case, we want to reclock.

2022-03-10 21:25 UTC, ChunMinChang requested changes
The idea of the logic here seems good, but I don't have the knowledge of the new `cubeb_resampler` design we are going to use. Could you give me some context?

2022-03-10 21:25 UTC, ChunMinChang commented on src/backend/mod.rs
> +            && false
This makes `should_use_aggregate_device` always returns `false`. Does it add for debugging only and forget to clean? or is there a reason to avoid using aggregate device?

2022-03-10 21:25 UTC, ChunMinChang commented on src/backend/mod.rs
> +                println!("Clock domains {} {}", input_domain, output_domain);
Replace `println!` by `cubeb_log!`.

I guess this is written when you're debugging. This reminds me https://github.com/mozilla/cubeb-coreaudio-rs/issues/70. We should have an easier way to enable the `cubeb_log` here.

2022-03-10 21:25 UTC, ChunMinChang commented on src/backend/mod.rs
> +        cubeb_log!("Coudn't determine clock domains for input and output");
`cubeb_log!("Coudn't determine clock domains for input or output")`?

Or, to have a better error messages, why don't we use
```rs
let input_domain = match get_clock_domain(self.input_device.id, DeviceType::INPUT) {
    Ok(domain) => domain,
    Err(e) => {
        cubeb_log!("Fail to get clock domains for input. Error: {}", e);
        return false;
    }
}

let output_domain = ... // Do the same

input_domain == output_domain
```

2022-03-10 21:25 UTC, ChunMinChang commented on src/backend/mod.rs
> +        let mut using_aggregate_device = false;
Instead of adding a `using_aggregate_device` here, we should make `aggregate_device: Option<AggregateDevice>`. That would be much easier to know if we have an aggregate_device in use or not, and worry-free to synchronize `aggregate_device` with `using_aggregate_device: bool`.

2022-03-14 14:03 UTC, padenot commented on src/backend/mod.rs
> +            && false
A mistake.

2022-03-14 14:04 UTC, padenot commented on src/backend/mod.rs
> +                println!("Clock domains {} {}", input_domain, output_domain);
I'm removing this anyways.

2022-03-14 14:06 UTC, padenot commented on src/backend/mod.rs
> +        cubeb_log!("Coudn't determine clock domains for input and output");
much better style, thanks.

2022-03-14 14:07 UTC, padenot commented on src/backend/mod.rs
> +        let mut using_aggregate_device = false;
Yes, better. But it will always be true now. I'll like to keep it like that (=have a function to enable/disable it, instead of cleaning everything up) for now, until we test more. There might be some circumstances where we don't want aggregate devices.

2022-03-14 14:08 UTC, padenot commented on src/backend/mod.rs
> +        let mut using_aggregate_device = false;
But we'll only know those possible circumstances after testing more with lots of devices (I've tested a lot already, but I only have so many devices).

2022-03-14 14:51 UTC, padenot commented
> The idea of the logic here seems good, but I don't have the knowledge of the new `cubeb_resampler` design we are going to use. Could you give me some context?
> 
> Now [mozilla/cubeb#690](https://github.com/mozilla/cubeb/pull/690) and [mozilla/cubeb-rs#62](https://github.com/mozilla/cubeb-rs/pull/62) are already merged, we should be able to make the tests work.

Generally, if the resampler finds that there are not enough input frames compared to output frames, it will very carefully strech the input audio.

Here is a practical example. If I connect a Microsoft Lifecam VX5000 to my Macbook Pro 2018, and use it as a microphone, and then open a duplex stream with the built-in headphones for the output, with the input and output at the same rate, I receive (on average, after running a long time), 0.04% more audio input frames that there are output frames rendered.

So my new system will detect this, and adjust a resampler for the input stream by a minuscule amount so that no extra buffering happens. If the opposite hapens (input doesn't deliver enough frames), it will stretch the audio.

But with the last patches in this PR, aggregate devices always work, and macOS reclocks for us, so this doesn't happen anymore. My resampling patches will be useful for Windows though.

2022-03-15 05:49 UTC, ChunMinChang requested changes
It seems these changes will always use hardware input channel count to get the input data, from all the (sub-)devices listed in the aggregate device, and then downmix them if necessary.

Can you describe a way so I can test this patch?

And, some commit order causes build error (e.g., `Make aggregate_device an Option` use `same_clock_domain` before it's implemented ) so we can only squash these commits before merging it. If you'd like "rebase and merge", please reorder them so it's easier to revert some of them if we are unlucky.

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/mod.rs
> +        cubeb_log!("Error callback: outframes is {}", outframes);
The commit message says "Logging statements that are in real-time threads should use cubeb_logv" but `cubeb_logv!` is applied here. Shouldn't this be `cubeb_logv!`?

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/mod.rs
> +    aggregate_device: Option<AggregateDevice>,
Oh this looks much better! Thanks!

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/mod.rs
> +            if input_hw_desc.mChannelsPerFrame < self.input_stream_params.channels() {
Is `input_hw_desc.mChannelsPerFrame` the max input channel count of the device?

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/mod.rs
> +    input_channels_to_ignore: u32,
> because of the way the aggregate device is setup.

Can we change how we set up the aggregate device so we don't need this?

I am not sure I understand why we need this. Is input channel count for an aggregate device the total of input channel count of all the devices in aggregate device?

If we only use aggregate device when the output device has no input and the input device has no output, do we still need this?


If this is unavoidable, it should be moved into `AggregateDevice`, since it is only used when stream is using `aggregate_device`

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/mod.rs
> +            }
Will `get_channel_count(in_dev_info.id, DeviceType::INPUT)` return sum of all the available input count of the devices listed in the aggregate device?

I find the above code duplicates in several places. Can you write a util function for them?

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/mod.rs
> -            && !is_device_a_type_of(self.output_device.id, DeviceType::INPUT)
This seems to cause regression for #13 and [BMO 1563475](https://bugzilla.mozilla.org/show_bug.cgi?id=1563475)

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/buffer_manager.rs
> +}
Nice!

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/buffer_manager.rs
> +    input_channels_to_ignore: usize,
What's the relationship between `channel_count`, `output_channels`, and `input_channels_to_ignore`?
`channel_count >= input_channels_to_ignore + output_channels`? Add an `assert!`?

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/buffer_manager.rs
> +    ) {
`assert!(channel_count >= input_channels_to_ignore + self.output_channels)`?

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/mod.rs
> +                stm.core_stream_data.input_desc.mChannelsPerFrame as usize,
Now `stm.core_stream_data.input_desc.mChannelsPerFrame` is the max hardware input channel count?

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/mod.rs
> +#[cfg(test)]
This could be removed if no other non-test code needs it.

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/mod.rs
> +            if self.input_channels_to_ignore != 0 {
if self.aggregate_device.is_some()

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/tests/manual.rs
> +    StreamType, TestDeviceInfo, TestDeviceSwitcher,
These code has been merged in trailblazer branch. Can you rebase your code?

2022-03-15 05:49 UTC, ChunMinChang commented on src/backend/tests/device_change.rs
> +            } else {
I don't think it's possible here. Are you running into this problem?

The `TestDevicePlugger` is implemented by an aggregate device, and it will be created when we have at least one input or output device. When the `plugger.unplug()` hads been executed, the new default device should be set to the original default device.

2022-03-15 14:18 UTC, padenot commented on src/backend/mod.rs
> +        cubeb_log!("Error callback: outframes is {}", outframes);
Yeah there are two problems.

First, I thought that `cubeb_logv!` was using the [async logging facility](https://searchfox.org/mozilla-central/source/media/libcubeb/src/cubeb_log.h#55-60), but that's not the case, and it's a big issue, because it means that logging isn't real-time safe. If I add a couple of logging statements to a debug build, and run with low-latency on my macbook 2018, it glitches...

So I'm going to send a patch to add it to `cubeb-rs`, but that's going to take a long time. And then I'm going to fix it here, so we'll be able to have proper logging from real-time threads.

Second, my message isn't correct. I conflated the messages that are frequent, and the message that are logged from the real-time thread, which are often the same messages, but not always.

Messages that aren't frequent, but from the real-time callback, should use normal async logging (non-verbose). But async logging isn't exposed in cubeb-rs so this is normal logging _for now_.

I filed https://github.com/mozilla/cubeb-rs/issues/66 for this and I'll drop this commit. Those message should go in normal log I was wrong.

2022-03-15 14:25 UTC, padenot commented on src/backend/mod.rs
> +    input_channels_to_ignore: u32,
No, we can't change this, it's how it works: an aggregate device puts two devices together as a single device. It's useful on its own. So if you aggregate a sound card that has 4 output and 4 input with a Bluetooth headset that has 2 output and 1 input, the resulting device has 6 output, 5 inputs, that's it.

If we aggregate a device that has just 2 channels of output with a device that has 1 channel of input, this number `input_chanenls_to_ignore` 0, and everything works well, no reordering will happen.

IMO this is not a something the aggregate device should do the `Aggregatedevice` class handles creation and sub-devices, nothing else, and especially nothing during processing: we don't want to special case aggregate device and regular devices during processing.

This is something that this cubeb backend wants to do: it wants to only ever use some specific channels in an aggregate device to implement a duplex stream with reclocking.

2022-03-15 14:38 UTC, padenot commented on src/backend/mod.rs
> +            }
> Will get_channel_count(in_dev_info.id, DeviceType::INPUT) return sum of all the available input count of the devices listed in the aggregate device?

Yes, if an aggregate device has two sub-devices, one with 2 channels of input one with 1 channel of input, calling this with the aggregate device ID will return 3.

I've added a commit turn a function for this.

2022-03-15 14:39 UTC, padenot commented on src/backend/mod.rs
> -            && !is_device_a_type_of(self.output_device.id, DeviceType::INPUT)
No, that's the whole point of this patch set, being able to use an aggregate device (and its benefits, mainly drift compensation) and using the intended device.

2022-03-15 14:40 UTC, padenot commented on src/backend/buffer_manager.rs
> +    input_channels_to_ignore: usize,
It's confusing, I'll rename and assert.

2022-03-15 15:23 UTC, padenot commented on src/backend/mod.rs
> +                stm.core_stream_data.input_desc.mChannelsPerFrame as usize,
Yes, always.

2022-03-15 15:24 UTC, padenot commented on src/backend/mod.rs
> +#[cfg(test)]
It's needed, I tried to remove it, but it broke `cargo test`.

2022-03-15 15:25 UTC, padenot commented on src/backend/tests/device_change.rs
> +            } else {
Yes, devices disappear from the test machine. Subsequently, trying to open a duplex stream fails (the state callback is called with `Error`). Locally it works well, it seems like.

2022-03-15 15:40 UTC, padenot commented on src/backend/mod.rs
> +            if self.input_channels_to_ignore != 0 {
No. We can have an aggregate device and not ignore any channels, when aggregating with an output device that only has output channels (not input channels).

2022-03-15 15:47 UTC, padenot commented
> Can you describe a way so I can test this patch?

Find a device (A) that has both input and output channels. Examples: the Blackhole virtual device, most pro audio soundcard that have input and output jacks to connect musical instruments. If using the Blackhole virtual device you'll want to listen to the output side via something else, e.g. a DAW. I'm using either Blackhole or an old Focusrite Scarlett 6i6.

Find a device (B) that has only an input channel, such as the built-in mic of the macbook.

Set the default output device to (A), the default input device to (B), run any cubeb example that pipes the input to the output, and you should hear the correct input device in the correct output, but with an aggregate device (so reclocking is done for us internally).

2022-03-15 16:13 UTC, ChunMinChang commented on src/backend/mod.rs
> +    input_channels_to_ignore: u32,
How do we know the `input_channels_to_ignore`, which is the input channel of the output-side device in aggregate device, always present in the first, before the input channel of the input-side device in aggregate device?

If we don't put `input_channels_to_ignore` in `Aggregatedevice`, can we put it in `input_buffer_manager` when  initializing it? It's a constant once we set `aggregate_device`

2022-03-15 16:15 UTC, padenot commented on src/backend/mod.rs
> +    input_channels_to_ignore: u32,
It's explained in the commit message: https://github.com/mozilla/cubeb-coreaudio-rs/pull/153/commits/fb8aeb99ba171b3ea4512266bb76c95a1888e0c8, and also I've done the change you suggested already.

2022-03-15 16:19 UTC, ChunMinChang commented on src/backend/mod.rs
> +            }
Sorry, I changed my mind.

Can use `get_channel_count(in_dev_info.id, DeviceType::INPUT)` as channel count and `self.input_hw_rate` as sample rate to create a temporary `StreamParams`, then use it to create `self.input_desc`? So we will end up having a `self.input_desc` with correct information we what and we can use it every where (`self.input_hw_rate` can probably go away).

2022-03-15 16:23 UTC, ChunMinChang commented on src/backend/mod.rs
> +#[cfg(test)]
I mean the `is_device_a_type_of` and its test can be removed since no production code needs it.

2022-03-15 16:29 UTC, ChunMinChang commented on src/backend/mod.rs
> +    input_channels_to_ignore: u32,
https://github.com/mozilla/cubeb-coreaudio-rs/blob/ca183a83c7c2d01749b97b26979bbd715b95dcd3/src/backend/aggregate_device.rs#L400-L401

I guess you mean here?

Just to make sure I understand. If we add input sub devices before output sub devices, then the first couple of input channel will be from the input sub devices, and we won't need `input_channels_to_ignore`, but we will end up having same situation in output side and need a  `output_channels_to_ignore`?

2022-03-15 16:36 UTC, padenot commented on src/backend/mod.rs
> +    input_channels_to_ignore: u32,
We'll still need `input_channels_to_ignore`, but the channel to ignore will be last, not first, in the buffers if the input device is first in the list.

2022-03-15 17:22 UTC, padenot commented on src/backend/mod.rs
> +            }
Not sure I understand what you mean by correct. How do you modify a `StreamParamRef` anyways ?

2022-03-16 01:20 UTC, ChunMinChang commented on src/backend/mod.rs
> +    input_channels_to_ignore: u32,
> if you aggregate a sound card that has 4 output and 4 input with a Bluetooth headset that has 2 output and 1 input, the resulting device has 6 output, 5 inputs, that's it.

It sounds like we need to ignore the extra channel count on output side as well?

2022-03-16 02:07 UTC, ChunMinChang commented on src/backend/mod.rs
> +    input_channels_to_ignore: u32,
> It's explained in the commit message: https://github.com/mozilla/cubeb-coreaudio-rs/commit/fb8aeb99ba171b3ea4512266bb76c95a1888e0c8, and also I've done the change you suggested already.

The `input_channels_to_ignore` is unnecessary now by the change, right?

2022-03-16 02:11 UTC, ChunMinChang commented on src/backend/mod.rs
> +            }
I think we can do something like this

```rs
let device_input_channels = get_channel_count(in_dev_info.id, DeviceType::INPUT)
     .unwrap_or(self.input_stream_params.channels());

// Set format description according to the input params.
let params = unsafe {
    let mut p = *self.input_stream_params.as_ptr();
    p.channels = device_input_channels;
    p.rate = input_hw_desc.mSampleRate as _;
    StreamParams::from(p)
 };

self.input_desc = create_stream_description(&params).map_err(|e| {
     cubeb_log!("({:p}) Setting format description for input failed.", self.stm_ptr);
     e
})?;

assert_eq!(self.input_desc.mSampleRate, input_hw_desc.mSampleRate);
assert_eq!(self.input_desc.mChannelsPerFrame, device_input_channels);
```

So `self.input_desc` will have the hardware information, and we can remove the `input_hw_rate` as well.

2022-03-16 07:35 UTC, ChunMinChang commented on src/backend/mod.rs
> +    input_channels_to_ignore: u32,
Suppose aggregate device _A_ contains device _X_ and device _Y_. Device _X_ has _m_ input channels and _n_ output channels. Device _Y_ has _p_ input channels and _q_ output channels. I think my question is:

1. If we add _X_ before _Y_ in aggregate device _A_, what are the first _i_ input channels and first _j_ output channels of _A_, where _0 < i <= m + p_, and _0 < j <= n + q_?
2. Similar as above, if we add _Y_ before _X_ in aggregate device _A_, what are the first _i_ input channels and first _j_ output channels of _A_?

2022-03-16 14:21 UTC, padenot commented on src/backend/mod.rs
> +    input_channels_to_ignore: u32,
1. We don't do that. We just grab all channels and figure out what channels we want to use. We always get all channels of input and only ever give the channels of the cubeb input device to the callback. For the output, we use the cubeb mixer to only use the channels of the cubueb output device (the others are `Silent`). 
2. We don't do that, but if we did, we'd get precisely the opposite ordering: we'd have to only take the first channels of the input buffers and discard the other channels (instead of taking the last), and we'd have to ask the cubeb mixer to put `Silent` to the channels corresponding to the output channels of the cubeb input device (which would be first), and only use the few last channels.

2022-03-16 15:29 UTC, padenot commented on src/backend/mod.rs
> +    input_channels_to_ignore: u32,
Actually I was wrong, we still need `input_channels_to_ignore` or something. We can have the following:

- Output device is 16in, 16out. Input device is 2in
- The user requests mono input
- `input_channels_to_ignore` is 16, number of channels total is 18, so there are 2 remaining channels. Now we need to down-mix those two channels to mono.

I've refactored the code because it's only needed at construction though, no need to store it in `CoreStreamData`.

2022-03-16 15:29 UTC, padenot commented on src/backend/mod.rs
> +            }
Yeah ok. Not sure that's better though, having an unsafe block in the middle of the code is not amazing.

2022-03-18 01:45 UTC, ChunMinChang requested changes
If we have no way to set the channel order for the aggregate device, using a remixer in BufferManager seems a feasible way to go.

The idea looks good. The proposed changes inspires me some ideas to make the code cleaner.

I have no way to add the _suggestion_ block for the unchanged code so I put all my suggestion here: https://github.com/ChunMinChang/cubeb-coreaudio-rs/commit/6408490256642f058e560ce32c2b14c70a39b55b

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +            self.input_desc = create_stream_description(&params).map_err(|e| {
I find we can do the similar thing for `output_desc`. Ideally, at the end we will merge `input_hw_rate` and `output_hw_rate` into `input_desc` and `output_desc`. And perhaps we should rename them to `input_dev_desc` and `output_dev_desc`

```rs
struct CoreStreamData<'ctx> {
    ...
    // Stream creation parameters.
    input_stream_params: StreamParams,
    output_stream_params: StreamParams,
    // Device settings for AudioUnits.
    input_dev_desc: AudioStreamBasicDescription,
    output_dev_desc: AudioStreamBasicDescription,
    ...
}
```

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
```suggestion
    fn get_device_channel_count(id: AudioDeviceID, devtype: DeviceType) -> Option<u32> {
            get_channel_count(id, devtype)
                .or_else(|e| {
                    cubeb_log!("Fail to get channel count for device {}. Error: {}", id, e);
                    get_device_stream_format(id, devtype).map(|f| f.mChannelsPerFrame)
                })
                .map_err(|e| {
                    cubeb_log!(
                        "Fail to get channel info from stream format for device {}. Error: {}",
                        id,
                        e
                    );
                })
                .ok()
        }
```
We can add a function that will be reused in both input side and output side, at the beginning of `setup`, to get the device channel count.

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +            if input_hw_desc.mChannelsPerFrame < self.input_stream_params.channels() {
I find this can be wrong when using aggregate device. `input_hw_desc.mChannelsPerFrame` here will be the total input channel count of all the sub-devices added in the aggregate device (e.g., we will get _m + n_ if the output device has _m_ input channels and the input device has _n_ input channels).

We should put something like this below `cubeb_log!("({:p}) Initialize input by device info: {:?}", ...)` and before `.. create_audiounit( ... ) ...` instead.

```rs
            let device_channel_count =
                get_device_channel_count(self.input_device.id, DeviceType::INPUT).unwrap_or(0);
            if device_channel_count < self.input_stream_params.channels() {
                return Err(Error::invalid_parameter());
            }
```

Ad we should also do the same thing for the output-side as well:
```rs
            let device_channel_count =
                get_device_channel_count(self.output_device.id, DeviceType::OUTPUT).unwrap_or(0);
            if device_channel_count < self.output_stream_params.channels() {
                return Err(Error::invalid_parameter());
            }
```

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +                .unwrap_or_else(|_| self.input_stream_params.channels());
```suggestion
```
We don't need this if we call `get_device_channel_count` in the beginning for input settings.

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +                p.channels = device_input_channels;
```suggestion
                p.channels = input_hw_desc.mChannelsPerFrame;
```

`input_hw_desc.mChannelsPerFrame` is the sum of all the input channel count of the devices added in the aggregate device.

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +            assert_eq!(self.input_desc.mChannelsPerFrame, device_input_channels);
```suggestion
```

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
```suggestion
assert!(input_hw_desc.mChannelsPerFrame >= device_channel_count);
// Notice: when we are using aggregate device, the input_hw_desc.mChannelsPerFrame is
// the total of all the input channel count of the devices added in the aggregate device.
// Due to our aggregate device settings, the data captured by the output device's input
// channels will be put in the beginning of the raw data given by the input callback.
```
We can add a line to make sure `input_hw_desc.mChannelsPerFrame` always have more or same number of channels we want.

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/buffer_manager.rs
> +    final_input_channels: usize,
```suggestion
fn process_data<T: Copy + std::ops::Add<Output = T>>(
    data: *mut c_void,
    frame_count: usize,
    input_channel_count: usize,
    input_channels_to_ignore: usize,
    output_channel_count: usize,
```

I'd like to unify the concept of `input` and `output` in this file, so I think we can rename this to `process_data` instead. See more in my comments below.

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/buffer_manager.rs
> +    ) -> BufferManager {
```suggestion
    format: SampleFormat,
        buffer_size_frames: usize,
        input_channel_count: usize,
        input_channels_to_ignore: usize,
        output_channel_count: usize,
    ) -> Self {
```

Since we need to do audio processing here, I'd like to match the concept of all the *input* and *output* in this file. The _input_channel*_ is the channel count of the data given to `push_data`, and the _output_channel_ is the channel count of the processed data we save in the internal ring buffer. Hence we should also rename the `LinearInputBuffer` to `LinearBuffer`

```rs
pub enum LinearBuffer {
    IntegerLinearBuffer(Vec<i16>),
    FloatLinearBuffer(Vec<f32>),
}
```

Does this make sense to you?

It would be better to put some comments somewhere as a note, in case we forget we we design `BufferManager` in this way.

```rs
    pub fn new(
        format: SampleFormat,
        buffer_size_frames: usize,
        input_channel_count: usize,
        input_channels_to_ignore: usize,
        output_channel_count: usize,
    ) -> Self {
        // We only support downmix in BufferManager, so output_channel_count must be equal to or less than the left channel count we can use.
        assert!(input_channel_count >= input_channels_to_ignore + output_channel_count);
        // 8 times the expected callback size, to handle the input callback being caled multiple
        //   times in a row correctly.
        let buffer_element_count = output_channel_count * buffer_size_frames as usize * 8;
        match format {
            SampleFormat::S16LE | SampleFormat::S16BE | SampleFormat::S16NE => {
                let ring = RingBuffer::<i16>::new(buffer_element_count);
                let (prod, cons) = ring.split();
                Self {
                    producer: IntegerRingBufferProducer(prod),
                    consumer: IntegerRingBufferConsumer(cons),
                    linear_buffer: IntegerLinearBuffer(Vec::<i16>::with_capacity(
                        buffer_element_count,
                    )),
                    input_channel_count,
                    input_channels_to_ignore,
                    output_channel_count,
                }
            }
            SampleFormat::Float32LE | SampleFormat::Float32BE | SampleFormat::Float32NE => {
                let ring = RingBuffer::<f32>::new(buffer_element_count);
                let (prod, cons) = ring.split();
                Self {
                    producer: FloatRingBufferProducer(prod),
                    consumer: FloatRingBufferConsumer(cons),
                    linear_buffer: FloatLinearBuffer(Vec::<f32>::with_capacity(
                        buffer_element_count,
                    )),
                    input_channel_count,
                    input_channels_to_ignore,
                    output_channel_count,
                }
            }
        }
    }
```

In addition, I'd like to replace the `if .. == ..` pattern by `match` pattern, which can automatically detect the `SampleFormat` cases we forget to handle.

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/buffer_manager.rs
> +    pub fn push_data(&mut self, input_data: *mut c_void, frame_count: usize, channel_count: usize) {
```suggestion
    pub fn push_data(&mut self, data: *mut c_void, frame_count: usize) {
```

`channel_count` is a fixed value after setup. We can move it to ctor.

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/buffer_manager.rs
> +    input_channels_to_ignore: usize,
```rs
pub struct BufferManager {
    consumer: RingBufferConsumer,
    producer: RingBufferProducer,
    linear_buffer: LinearBuffer,
    // The number of channels in the interleaved data given to push_data
    input_channel_count: usize,
    // The number of channels that needs to be skipped in the beginning of input_channel_count
    input_channels_to_ignore: usize,
    // The number of channels we actually needs, which is also the channel count of the
    // processed data stored in the internal ring buffer.
    output_channel_count: usize,
}
```

To unify the concept of _input_, I'd to have something similar as above

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +            };
```suggestion
```
We can use `self.self.input_dev_desc.mChannelsPerFrame - device_channel_count` to get the ignored channel count instead.

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
>              ));
```suggestion
           /// When we use the aggregate device, the self.input_dev_desc.mChannelsPerFrame is the
            // total input channel count of all the device added in the aggregate device. However,
            // we only need the audio data captured by the requested input device, so we need to
            // ignore some data captured by the audio input of the requested output device (e.g.,
            // the requested output device is a USB headset with built-in mic), in the beginning of
            // the raw data taken from input callback.
            self.input_buffer_manager = Some(BufferManager::new(
                self.input_stream_params.format(),
                SAFE_MAX_LATENCY_FRAMES as usize,
                self.input_dev_desc.mChannelsPerFrame as usize,
                (self.input_dev_desc.mChannelsPerFrame - device_channel_count) as usize,
                self.input_stream_params.channels() as usize,
            ));
```

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +            );
```suggestion
            input_buffer_manager
                .push_data(input_buffer_list.mBuffers[0].mData, input_frames as usize);
```

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +    let input_hw_rate = stm.core_stream_data.input_desc.mSampleRate as u64;
```suggestion
    let input_hw_rate = stm.core_stream_data.input_dev_desc.mSampleRate as u64;
```

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +        let input_channels = stm.core_stream_data.input_stream_params.channels() as usize;
```suggestion
        let input_channels = input_buffer_manager.channel_count() as usize;
```

We should add a function in `BufferManager` to get this instead:
```rs
impl BufferManager {
    ...
    pub fn channel_count(&self) -> usize {
        self.output_channel_count
    }
    ...
```

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +            stm.core_stream_data.input_desc.mSampleRate,
```suggestion
            stm.core_stream_data.input_dev_desc.mSampleRate,
```

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +                &self.input_desc,
```suggestion
                &self.input_dev_desc,
```

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +            params.rate = self.input_desc.mSampleRate as u32;
```suggestion
            params.rate = self.input_dev_desc.mSampleRate as u32;
```

2022-03-18 01:45 UTC, ChunMinChang commented on src/backend/mod.rs
> +        let hw_rate = self.core_stream_data.input_desc.mSampleRate as u32;
```suggestion
        let hw_rate = self.core_stream_data.input_dev_desc.mSampleRate as u32;
```

2022-03-18 01:48 UTC, ChunMinChang requested changes

2022-03-18 01:48 UTC, ChunMinChang commented on src/backend/tests/device_change.rs
> +            } else {
I am not sure if we need this. The test passed in https://github.com/ChunMinChang/cubeb-coreaudio-rs/commit/6408490256642f058e560ce32c2b14c70a39b55b

2022-03-18 12:46 UTC, padenot commented on src/backend/mod.rs
> +            if input_hw_desc.mChannelsPerFrame < self.input_stream_params.channels() {
For the output side, it's well-defined, we have a mixer that will down-mix properly because there are mapping information (it's useful to play, say, 5.1 audio on stereo). For input, definitely yes, your version is better.

2022-03-18 13:08 UTC, padenot commented on src/backend/tests/device_change.rs
> +            } else {
I'll back out and see.

2022-03-18 13:10 UTC, padenot commented on src/backend/mod.rs
> +                .unwrap_or_else(|_| self.input_stream_params.channels());
They are different, I've added a comment.

2022-03-18 13:16 UTC, padenot commented on src/backend/mod.rs
What's the difference with what we have? We need both the channel count of the aggregate, and the input device, that doesn't really help.

2022-03-18 13:17 UTC, padenot commented on src/backend/mod.rs
> +                p.channels = device_input_channels;
Yes, this is the point. I've renamed some variables to make this clearer.

2022-03-18 14:01 UTC, padenot commented
Well this branch has my fix.

2022-03-18 14:08 UTC, padenot commented
You know you can push to other people's PR directly, yes? It's a lot easier this way.

I've actually reverted my patch that fixes the `unwrap`, here is a failure: https://github.com/mozilla/cubeb-coreaudio-rs/runs/5601532591?check_suite_focus=true#step:6:526

2022-03-22 00:53 UTC, ChunMinChang approved these changes
It seems we finally fix the mystery crash in `test_destroy_duplex_stream_after_unplugging_a_nondefault_input_device` by no adding one aggregate device into another aggregate device? Nice!

2022-03-22 10:31 UTC, merged