Use a VoiceProcessingIO AudioUnit with bypass enabled instead of a regular AudioUnit on top of a drift-corrected aggregate device when in VOICE mode
mozilla/cubeb-coreaudio-rs pull request #185
Opened 2023-10-11 11:06 UTC by Pehrsons

The drift corrected aggregate device is resulting in distortions due to drift, and we do not really understand why.
The VoiceProcessingIO AudioUnit handles drift properly.

This is the workaround fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1670633.

Note that the VoiceProcessingIO AudioUnit enables system wide ducking on other output streams while running.
We set it to bypass mode for now since there is not yet an API to toggle processing features dynamically, as would be needed by Firefox through MediaStreamTrack.applyConstraints.

2023-10-13 20:23 UTC, Pehrsons commented on src/backend/mod.rs
> +                .contains(StreamPrefs::VOICE);
I'm thinking we should do this regardless of `StreamPref::VOICE`. I'm not noticing *any* added latency (with nightly and release running side by side) in bypass mode. Thoughts?

2023-10-14 16:34 UTC, ChunMinChang requested changes
Thanks for adding VoiceProcessing support!

Since VoiceProcessing code is used behind a pref, they are not tested yet. It would be great to have some tests for this. 

I see some issues with Blackhole devices, but the tests can be run locally without BlackHole as long as it has built-in or plugged audio devices, although some device-related test settings (in Git Actions) might need to be tweaked. 

Some complicated code added to the `setup` can reduce the readability. It's better to simplify the code to lower the long-term maintenance effort.

2023-10-14 16:34 UTC, ChunMinChang commented on src/backend/tests/utils.rs
> -            let private_value: i32 = 1;
Is the created aggregate device exposed to another process? Why is this necessary?

2023-10-14 16:34 UTC, ChunMinChang commented on src/backend/mod.rs
> +                .contains(StreamPrefs::VOICE);
Do we have any test that uses `StreamPrefs::VOICE`? A *VoiceProcessingIO* test is necessary for this PR.

If the input device's `AudioDeviceID` is the same as the output device's, is the *VoiceProcessingIO* still needed? (Some Plantronics headset with mic gives the same input and output `AudioDeviceID`)

2023-10-14 16:34 UTC, ChunMinChang commented on src/backend/mod.rs
> -        componentSubType: kAudioUnitSubType_RemoteIO,
This definitely looks better! Thanks!

2023-10-14 16:34 UTC, ChunMinChang commented on src/backend/mod.rs
> +fn create_typed_audiounit(sub_type: ::std::os::raw::c_uint) -> Result<AudioUnit> {
`c_uint` can be used here with changing `use std::os::raw::c_void` to `std::os::raw::{c_void, c_uint}` in the beginning lines of the file.

2023-10-14 16:34 UTC, ChunMinChang commented on src/backend/mod.rs
> +                },
```suggestion
self.input_dev_desc.mChannelsPerFrame.saturating_sub(device_channel_count)
```
Nice catch! [`saturating_sub`](https://doc.rust-lang.org/std/primitive.u32.html#method.saturating_sub) is there to do this job.

2023-10-14 16:34 UTC, ChunMinChang commented on src/backend/mod.rs
> +                        channels.push(mixer::Channel::FrontRight);
The `mixer::Channel::Silence` should be appended for more than two channels. But what the channel order should be?

2023-10-14 16:34 UTC, ChunMinChang commented on src/backend/mod.rs
> +        })?;
The code is hard to read.`setup` is complex enough (although we never find time to fix `clippy::cognitive_complexity`), and the `or_else` pattern brings some unhelpful `Err`s that increases the reading difficulty. To simplify the code, `if let` is a more practical choice. 

On the other hand, with the changes made here, `should_use_aggregate_device` should be removed. Even though `should_use_aggregate_device` returns `true` and devices are eligible to create an aggregate device, the VoiceProcessIO can be used instead. Or the function needs to be renamed, at least.

Using a function for AudioUnit-creation makes `setup` more readable, something like this:

```rust
fn create_audiounits(&mut self) -> Result<(device_info, device_info)> {
    // Create an AudioUnit:
    // - If we're eligible to use voice processing, try creating a VoiceProcessingIO AudioUnit.
    // - If we should use an aggregate device, try creating one and input and output AudioUnits next.
    // - As last resort, create regular AudioUnits. This is also the normal non-duplex path.

    let should_use_voice_processing_unit = self.has_input()
        && self.has_output()
        && self
            .input_stream_params
            .prefs()
            .contains(StreamPrefs::VOICE);

    let should_use_aggregate_device = {
        // ..... bring code here
        // Only use an aggregate device when the device are different.
        self.has_input()
            && self.has_output()
            && self.input_device.id != self.output_device.id
            && !either_already_aggregate
    };

    if should_use_voice_processing_unit {
        if let Ok(au) = create_voiceprocessing_audiounit(&self.input_device, &self.output_device) {
            self.input_unit = au;
            self.output_unit = au;
            return Ok((self.input_device.clone(), self.output_device.clone()));
        }
        // ... error logs here
    }

    if should_use_aggregate_device {
        if let Ok(device) = AggregateDevice::new(self.input_device.id, self.output_device.id) {
            let agg_in_dev_info = device_info {
                id: device.get_device_id(),
                ..self.input_device
            };
            let agg_out_dev_info = device_info {
                id: device.get_device_id(),
                ..self.output_device
            };
            if let (Ok(in_au), Ok(out_au)) = (
                create_audiounit(&agg_in_dev_info),
                create_audiounit(&agg_out_dev_info),
            ) {
                self.input_unit = in_au;
                self.output_unit = out_au;
                self.aggregate_device = Some(device);
                return Ok((agg_in_dev_info, agg_out_dev_info));
            }
        }
        // ... error logs here
    }

    // Regular AudioUnit creation here.
    self.input_unit = if self.has_input() {
        create_audiounit(&self.input_device).map_err(|e| {
            // ... error logs here
            cubeb_log!(
                "({:p}) Failed to create regular AudioUnit for input.",
                self.stm_ptr
            );
            e
        })?
    } else {
        ptr::null_mut()
    };

    self.output_unit = if self.has_output() {
        create_audiounit(&self.output_device).map_err(|e| {
            cubeb_log!(
                "({:p}) Failed to create regular AudioUnit for output.",
                self.stm_ptr
            );
            e
        })?
    } else {
        ptr::null_mut()
    };

    Ok((self.input_device.clone(), self.output_device.clone()))
}
```

so the readers don't need to know the details in the `setup`:

```rust
let (in_dev_info, out_dev_info) = self.create_audiounits()?;
let using_voice_processing_unit = self.input_unit == self.output_unit;
```

2023-10-14 16:34 UTC, ChunMinChang commented on src/backend/mod.rs
> +            }?;
```suggestion
            let input_unit = if self.has_input() {
                create_audiounit(&in_dev_info).map_err(|e| {
                    cubeb_log!("({:p}) Failed to create regular AudioUnit for input.", self.stm_ptr);
                    e
                })?
            } else {
                ptr::null_mut()
            };
```

The `?` can be put after `create_audiounit` so `Ok` can be removed in the `else` block.

Same for output side.

2023-10-14 16:34 UTC, ChunMinChang commented on src/backend/mod.rs
> +                    res
In the voice-processing case, the code tries to find the channel-layout by:
1. `get_current` with `VoiceProcessingIO` AU (always fail)
2. `get_current` with a dummy output AU
3. `get_preferred` with a dummy output AU (always work?)
4.  `get_preferred` with `VoiceProcessingIO`

Why are 2 and 3 prioritized over 4? Shouldn't the code respect the `VoiceProcessingIO` first? If 2 or 3 always work, then 4 never called. Does `VoiceProcessingIO` support `kAudioDevicePropertyPreferredChannelLayout`, or it always fails?

If 4 always fails or 4 should be prioritized, then the following code:

```rs
fn get_channel_layout(output_unit: AudioUnit) -> Result<Vec<mixer::Channel>> {
    audiounit_get_current_channel_layout(output_unit)
        .or_else(|_| audiounit_get_preferred_channel_layout(output_unit))
}

// CoreStreamData's method
fn get_output_channel_layout(&self) -> Result<Vec<mixer::Channel>> {
    get_channel_layout(self.output_unit).or_else(|e| {
        // If it's VoiceProcessingIO case, try standing up a regular AudioUnit and query that.
        if self.input_unit == self.output_unit {
            let mut dedicated_unit = create_audiounit(&self.output_device)?;
            let res = get_channel_layout(dedicated_unit);
            audio_unit_uninitialize(dedicated_unit);
            dispose_audio_unit(dedicated_unit);
            dedicated_unit = ptr::null_mut();
            return res;
        }
        Err(e)
    })
}
```

can be used to simplify the code in `setup`:
```rs
let device_layout = self.get_output_channel_layout().unwrap_or_default();
```

2023-10-16 14:45 UTC, Pehrsons commented
> Since VoiceProcessing code is used behind a pref

Define pref?

2023-10-16 14:50 UTC, Pehrsons commented on src/backend/tests/utils.rs
> -            let private_value: i32 = 1;
https://github.com/mozilla/cubeb-coreaudio-rs/pull/185/commits/a6db1da3233a0773ffb09bda3e9ad1892cd2e1fc

2023-10-16 14:52 UTC, Pehrsons commented on src/backend/tests/utils.rs
> -            let private_value: i32 = 1;
relevant output (without the change linked above):
```
      Running unittests src/lib.rs (target/debug/deps/cubeb_coreaudio-18079467f3b516b6)

running 1 test
Before plugging, default Input device is 120
Create plugger device: 162 for Input
After plugging, default Input device is 120

Input devices
--------------------
 125: AppleUSBAudioEngine:Burr-Brown from TI:USB audio CODEC:3400000:2
	uid: USB audio CODEC
 135: AppleUSBAudioEngine:Microsoft:Microsoft® LifeCam HD-3000:3112000:3
	uid: Microsoft® LifeCam HD-3000
  55: BlackHole2ch_UID
	uid: BlackHole 2ch
 120: BuiltInMicrophoneDevice
	uid: MacBook Pro Microphone
 162: org.mozilla.TestAggregateDevice_1697467741403804000
	uid: TestAggregateDevice_1697467741403804000

Current default Input device is 120
state: started
Stream runs on the device 162 for Input
test backend::tests::device_change::test_destroy_input_stream_after_unplugging_a_default_input_device has been running for over 60 seconds
```

2023-10-16 14:56 UTC, Pehrsons commented on src/backend/mod.rs
> +                .contains(StreamPrefs::VOICE);
Not here, I'll add some. In gecko we might, but I suppose we don't have virtual devices on mac there.

Does identical device ids guarantee no drift? If so we don't need VPIO for the sake of handling drift. But once we have the API to allow **enabling** voice processing features we'll still need it (and be able to toggle it on the fly).

2023-10-16 14:59 UTC, Pehrsons commented on src/backend/mod.rs
> +                },
Ooh!

2023-10-16 15:07 UTC, Pehrsons commented on src/backend/mod.rs
> +                        channels.push(mixer::Channel::FrontRight);
Yes, well, overtaken by https://github.com/mozilla/cubeb-coreaudio-rs/pull/185/commits/5c801e8006bba9ee857ce112d22e81491fbd82b7.

2023-10-16 15:10 UTC, Pehrsons commented on src/backend/mod.rs
> +                    res
4 doesn't fail but IIRC it returns garbage. Locally I've seen `7` for a mono input. `13` for another. I'll look more at this later.

2023-10-16 20:04 UTC, Pehrsons commented on src/backend/mod.rs
> +                .contains(StreamPrefs::VOICE);
Actually, I'll change to using VPIO regardless of `StreamPrefs::VOICE`, because 1) I see no difference at all in latency, and 2) aggregate devices just doesn't handle drift well (at all it seems, at least if the input device is slower than the output device).
Side effects of this should be limited to: 1) the time it takes to init the VPIO AudioUnit is longer, and 2) audio ducking is active while the VPIO AudioUnit is running. I expect 2) to be a good thing in most cases. It is better than audio distortions due to drift in other cases.
As a bonus, that will fix the testing situation.

2023-10-16 20:34 UTC, Pehrsons commented on src/backend/mod.rs
> +                    res
In case we are using VPIO, should we just ditch 1 and do 2 and 3? Would be simpler.

2023-10-18 02:30 UTC, ChunMinChang commented on src/backend/mod.rs
> +                .contains(StreamPrefs::VOICE);
By definition, [`CUBEB_STREAM_PREF_VOICE`](https://github.com/mozilla/cubeb/blob/f1bfefbbd412eaa0fe89f5afb3c11b427dc2446a/include/cubeb/cubeb.h#L238-L244) is mainly used to change the device selection, like [here](https://github.com/mozilla/cubeb/blob/f1bfefbbd412eaa0fe89f5afb3c11b427dc2446a/src/cubeb_wasapi.cpp#L2679-L2681). Different settings may be applied in this case though, e.g., for resampler [on WASAPI](https://github.com/mozilla/cubeb/blob/f1bfefbbd412eaa0fe89f5afb3c11b427dc2446a/src/cubeb_wasapi.cpp#L2622-L2623) (maybe we should apply here as well?). Since using vpio doesn't affect device selection from the user's perspective, I don't have a strong opinion, and I am not aware that Gecko has non-WebRTC cases for duplex stream usage. @padenot, @kinetiknz: do you know if the duplex stream is used for non-WebRTC cases (e.g., WebAudio or dolphin emulator)?

2023-10-18 02:31 UTC, ChunMinChang commented on src/backend/mod.rs
> +                    res
Using 2 and 3 seems a reasonable choice if 4 returns a garbage value.

2023-10-18 02:34 UTC, ChunMinChang commented
> > Since VoiceProcessing code is used behind a pref
> 
> Define pref?

What I meant was that whether the vpio is set is by checking the `cubeb_stream_prefs`'s flag.

2023-10-18 02:36 UTC, ChunMinChang commented on src/backend/tests/utils.rs
> -            let private_value: i32 = 1;
Weird. I should upgrade to MacOS 14 to check this. In that case, can you update the comment: `// This device is private to the process creating it.` as well? IIRC, this comment is for `private_value`.

2023-10-18 14:36 UTC, padenot commented on src/backend/mod.rs
> +            // XXX
Fine for now.

2023-10-18 14:36 UTC, padenot commented on src/backend/mod.rs
> -        // It's impossible to create an aggregate device from an aggregate device, and it's
This I want to try again on an older macOS version. I remember having a problem and adding this code.

2023-10-18 14:36 UTC, padenot commented on src/backend/mod.rs
> +                .contains(StreamPrefs::VOICE);
We can land this now, and I'll have folks re-test latency for us. Firefox is used for non-voice use-case, but it isn't clear if VPIO is suitable for non-voice use-case.

The documentation says "can" and is open-ended and not prescriptive.

2023-10-24 08:57 UTC, Pehrsons commented on src/backend/mod.rs
> +        })?;
I added some handling to dispose created audio units on failure, otherwise it looked good. Thanks for the improvements!

2023-10-24 09:04 UTC, Pehrsons commented on src/backend/mod.rs
> -        // It's impossible to create an aggregate device from an aggregate device, and it's
I have reverted this, so should be OK.

2023-10-24 13:36 UTC, Pehrsons commented on src/backend/mod.rs
> +            || data_callback.is_none()
A bit of a behavior change here, note.

2023-10-25 09:47 UTC, Pehrsons commented on src/backend/mod.rs
> +                    1
Another behavior change here in that input will always be mono.

2023-10-25 09:48 UTC, Pehrsons commented on src/backend/mod.rs
> +                    p.rate = output_hw_desc.mSampleRate as _;
Another behavior change here in that the output rate will be limited to the input hw rate (regardless of configuration)

2023-10-27 00:44 UTC, ChunMinChang reviewed
The patches look good. However, I'd like to identify where the crash in the test failures is and its cause, in case the crash happens in the wild.

2023-10-27 00:44 UTC, ChunMinChang commented on src/backend/mod.rs
> +            dispose_audio_unit(unit);
Nice catch, thanks!

2023-10-27 00:44 UTC, ChunMinChang commented on src/backend/mod.rs
> +
I wonder why `enable_audiounit_scope` is not called.

2023-10-27 00:44 UTC, ChunMinChang commented on src/backend/mod.rs
> +            !self.input_unit.is_null() && self.input_unit == self.output_unit;
We can move this into a function. This check appears in other places like `close` or `start_audiounits`.

2023-10-27 00:44 UTC, ChunMinChang commented on src/backend/mod.rs
> +    fn get_output_channel_layout(&self) -> Result<Vec<mixer::Channel>> {
```rs
assert!(!self.output_unit.is_null())
```

2023-10-27 16:21 UTC, ChunMinChang commented on src/backend/mod.rs
> +        let should_use_voice_processing_unit = self.has_input() && self.has_output();
what if the input or output is an aggregate device? Does it make a difference?

2023-10-27 17:13 UTC, ChunMinChang commented on run_device_tests.sh
> +# FIXME: The test will hang if the default input or output is an aggregate device (and VoiceProcessingIO is)
This can be enabled after excluding `VOICEPROCESSING_AGGREGATE_DEVICE_NAME` in the test devices.: https://github.com/mozilla/cubeb-coreaudio-rs/actions/runs/6669698195 

Changing `DeviceFilter` into:

```rs
pub enum DeviceFilter {
    ExcludeCubebAggregateAndVPIO,
    IncludeAll,
}
```

and updating `test_get_all_devices` to:

```rs
...
match filter {
    DeviceFilter::ExcludeCubebAggregateAndVPIO => {
        devices.retain(|&device| {
            if let Ok(uid) = get_device_global_uid(device) {
                let uid = uid.into_string();
                !uid.contains(PRIVATE_AGGREGATE_DEVICE_NAME)
                    && !uid.contains(VOICEPROCESSING_AGGREGATE_DEVICE_NAME)
            } else {
                true
            }
        });
    }
    _ => {}
}
```

makes `test_register_device_changed_callback_to_check_default_device_changed_duplex` on my local machine and git actions

2023-10-27 17:21 UTC, Pehrsons commented on src/backend/mod.rs
> +        let should_use_voice_processing_unit = self.has_input() && self.has_output();
then creation of vpio fails and we try to create an aggregate device instead.

2023-10-27 17:25 UTC, Pehrsons commented on run_device_tests.sh
> +# FIXME: The test will hang if the default input or output is an aggregate device (and VoiceProcessingIO is)
Woot, thanks! I'll fix.

2023-11-02 20:45 UTC, Pehrsons commented on run_device_tests.sh
> +# FIXME: The test will hang if the default input or output is an aggregate device (and VoiceProcessingIO is)
I'm not having the same luck. See here the logs, plus a new `println!()` in `test_device_channels_in_scope`.

```
running 1 test
NOTICE: The test will hang if the default input or output is an aggregate device.
We will fix this later.
id: 55, scope: input, channels: 2
id: 120, scope: input, channels: 1
id: 113, scope: input, channels: 0
id: 55, scope: output, channels: 2
id: 120, scope: output, channels: 0
id: 113, scope: output, channels: 2
mod.rs:2205: Use global latency 512 instead of the requested latency 4096.
mod.rs:199: Using the system default device
mod.rs:199: Using the system default device
mod.rs:2543: Input device ID: 120 (aggregate: false)
mod.rs:2557: Output device ID: 120 (aggregate: false)
mod.rs:2579: (0x12780b3d0) Using VoiceProcessingIO AudioUnit
mod.rs:2729: (0x12780b3d0) Initializing input by device info: device_info { id: 120, flags: device_flags(DEV_INPUT | DEV_SELECTED_DEFAULT) }
mod.rs:2741: (0x12780b3d0) Opening input side: rate 48000, channels 1, format Float32LE, layout FRONT_CENTER, prefs (empty), latency in frames 512, voice processing true.
mod.rs:2771: (0x12780b3d0) Input hardware description: AudioStreamBasicDescription { mSampleRate: 48000.0, mFormatID: 1819304813, mFormatFlags: 41, mBytesPerPacket: 4, mFramesPerPacket: 1, mBytesPerFrame: 4, mChannelsPerFrame: 7, mBitsPerChannel: 32, mReserved: 0 }
mod.rs:1229: The buffer frame size of AudioUnit 0x97cc30ae for INPUT is already 512
mod.rs:2891: (0x12780b3d0) Input audiounit init with device 120 successfully.
mod.rs:2901: (0x12780b3d0) Initialize output by device info: device_info { id: 55, flags: device_flags(DEV_OUTPUT | DEV_SELECTED_DEFAULT) }
mod.rs:2907: (0x12780b3d0) Opening output side: rate 44100, channels 2, format Float32LE, layout FRONT_LEFT | FRONT_RIGHT, prefs (empty), latency in frames 512, voice processing true.
mod.rs:2937: (0x12780b3d0) Output hardware description: AudioStreamBasicDescription { mSampleRate: 48000.0, mFormatID: 1819304813, mFormatFlags: 9, mBytesPerPacket: 8, mFramesPerPacket: 1, mBytesPerFrame: 8, mChannelsPerFrame: 2, mBitsPerChannel: 32, mReserved: 0 }
mod.rs:3479: (0x12780b3d0) get_output_channel_layout with a VoiceProcessingIO output unit. Trying a dedicated unit.
mod.rs:2986: (0x12780b3d0 Using output device channel layout [FrontLeft, FrontRight]
mod.rs:1229: The buffer frame size of AudioUnit 0x97cc30ae for OUTPUT is already 512
mod.rs:3077: (0x12780b3d0) Output audiounit init with device 55 successfully.
mod.rs:2266: (0x12780b3d0) Cubeb stream init successful.

Input devices
--------------------
id: 55, scope: input, channels: 4
id: 120, scope: input, channels: 3
id: 113, scope: input, channels: 6
  55: BlackHole2ch_UID
	uid: BlackHole 2ch
 120: BuiltInMicrophoneDevice
	uid: MacBook Pro Microphone
 113: BuiltInSpeakerDevice
	uid: MacBook Pro Speakers

Switch device for Input: 120 -> 113
id: 113, scope: input, channels: 6
test backend::tests::device_change::test_register_device_changed_callback_to_check_default_device_changed_duplex has been running for over 60 seconds
```

I can see it working in CI since there's only a BlackHole device, but you say it works locally for you?
It's weird that it reports 6 input channels for an output device but yeah 🤷 
I'll see if I can find a workaround.

2023-11-02 23:36 UTC, Pehrsons commented on run_device_tests.sh
> +# FIXME: The test will hang if the default input or output is an aggregate device (and VoiceProcessingIO is)
Ok, I have a fix based on [this](https://searchfox.org/wubkat/rev/67be1e0883407c894c71a4c903e5030059a7b5e9/Source/WebCore/platform/mediastream/mac/CoreAudioCaptureDeviceManager.cpp#117).

2023-11-03 00:01 UTC, Pehrsons commented on src/backend/mod.rs
> +
Same [in webkit](https://searchfox.org/wubkat/rev/67be1e0883407c894c71a4c903e5030059a7b5e9/Source/WebCore/platform/mediastream/mac/CoreAudioSharedUnit.cpp#297-315). Both scopes are enabled by default I guess.

2023-11-16 18:17 UTC, padenot approved these changes
Let's try this -- but we might need to revert back to "regular" audiounit when _not_ doing using the stream for voice if latency is increased.

2023-11-16 18:17 UTC, padenot commented on src/backend/mod.rs
> +                    p.rate = output_hw_desc.mSampleRate as _;
This is fine. It's also the case on e.g. some android and windows.

2023-11-16 18:18 UTC, padenot commented
Stealing the review from @ChunMinChang who is busy, this has been reworked significantly and there are green tests now (locally and on CI).

2023-11-16 18:19 UTC, padenot commented on src/backend/mod.rs
> +                    1
We'll see about this later.

2023-11-16 18:22 UTC, padenot commented on src/backend/mod.rs
> +                .contains(StreamPrefs::VOICE);
I had missed the question. Web Audio API can use non-voice (e.g. in a musical context, to record an instrument or something).  But we need to be prepare to switch back to non vpio if latency isn't as good, and this is fine.

2023-11-16 18:22 UTC, merged