Add audio dumping, make audio output with professional soundcard work
mozilla/cubeb-coreaudio-rs pull request #217
Opened 2024-04-16 16:19 UTC by padenot

Disregard the build error, I need cubeb-rs and cubeb upstream things to merge first. The first three commits are rebased + changed commit message but are essentially merged commits from @Pehrsons (please double-check regardless). We might want to drop the `test_tone.rs` change from this series.

`misc` is not to be reviewed, and I'll drop it.

2024-04-22 07:30 UTC, Pehrsons requested changes
Also [DEBUG: switch test_tone to output 11 channels](https://github.com/mozilla/cubeb-coreaudio-rs/pull/217/commits/fca86f5d1a1db24c3d85e6af47797a73de0fcbd6) should not be landed. Please fix the stack and I'll look again.

2024-04-22 09:29 UTC, padenot commented
Yes, sorry. I need other series to merge before this one can run correctly.

2024-04-25 10:22 UTC, Pehrsons requested changes
In the commit `Add a test for enabling logging` it was not meant for the logging stuff to land. But if we want it could we only compile log.c in a dev or test environment? Do also note @ChunMinChang is the original author of that bit.

Other comments inline.

2024-04-25 10:22 UTC, Pehrsons commented on src/backend/mod.rs
> +cfg_if! {
Did I read the docs right in that `cfg_if` is only needed when you want `else` blocks in your cfg'd code?

2024-04-25 10:22 UTC, Pehrsons commented on src/backend/mod.rs
> +                }
Indentation seems weird.

2024-04-25 10:22 UTC, Pehrsons commented on src/backend/tests/manual.rs
> +    test_ops_stream_operation, Scope, StreamType, TestDeviceInfo, TestDeviceSwitcher,
Either skip these entirely, or put the call to `test_enable_log` behind a user choice, since the terminal will be spammed with logging otherwise, and the terminal is where users interact with the tester program.

2024-04-25 12:45 UTC, padenot commented on src/backend/tests/manual.rs
> +    test_ops_stream_operation, Scope, StreamType, TestDeviceInfo, TestDeviceSwitcher,
Skipped

2024-04-25 14:18 UTC, Pehrsons approved these changes
Thanks! One issue and a nit really, fix at your own discretion.

2024-04-25 14:18 UTC, Pehrsons commented on src/backend/mod.rs
> +            return NO_ERR;
this line needs to go outside the cfg block

2024-04-25 14:18 UTC, Pehrsons commented on src/backend/tests/api.rs
> -        (vec![kAudioObjectUnknown], vec![mixer::Channel::Silence]),
Don't we want to keep this case but with `s/Silence/Discrete` ?

2024-04-25 14:54 UTC, padenot commented on src/backend/tests/api.rs
> -        (vec![kAudioObjectUnknown], vec![mixer::Channel::Silence]),
`kAudioObjectUnknown` vs. `kAudioChannelLabel_Unknown`. If the former happens, I want to know about it.

2024-04-25 14:54 UTC, padenot commented on src/backend/tests/api.rs
> -        (vec![kAudioObjectUnknown], vec![mixer::Channel::Silence]),
(using the `eprintln!(...)`)

2024-04-25 15:51 UTC, merged