When playing mono or stereo, address the channels by name rather than using 0 and 1
mozilla/cubeb-coreaudio-rs pull request #222
Opened 2024-05-27 14:19 UTC by padenot

This should fix https://bugzilla.mozilla.org/show_bug.cgi?id=1474175.

2024-05-27 15:20 UTC, Pehrsons requested changes

2024-05-27 15:20 UTC, Pehrsons commented on src/backend/mod.rs
> +                && self.output_stream_params.channels() == 2
This doesn't cover mono.

2024-05-27 17:14 UTC, Pehrsons approved these changes
This kind of thing seems very likely to go undetected if regressed. I'd love to have a test case, see an idea inline.
I'll leave it to your own discretion, r+.

2024-05-27 17:14 UTC, Pehrsons commented on src/backend/mod.rs
> +                    layout.mChannelLayoutTag = kAudioChannelLayoutTag_Mono;
Still, this will never get hit.

2024-05-27 17:14 UTC, Pehrsons commented on src/backend/tests/manual.rs
> +fn test_tone() {
We might be able to test this with `blackhole-16ch` by setting `kAudioDevicePropertyPreferredChannelsForStereo` to something that is not `[0, 1]`.
Maybe even on `blackhole-2ch` by just flipping left and right, i.e. setting that property to `[1, 0]`.

2024-05-28 14:58 UTC, padenot commented on src/backend/tests/manual.rs
> +fn test_tone() {
Turns out this isn't possible unfortunately, so we'll have to rely on manual testing for this.

2024-05-28 15:27 UTC, merged

2024-05-28 23:55 UTC, uberjay commented
For someone totally unfamiliar with the Firefox release process -- when might this fix make its way into something I can try?

2024-05-29 11:00 UTC, Pehrsons commented
It will be in Nightly soon. Follow along in https://bugzilla.mozilla.org/show_bug.cgi?id=1474175.

2024-05-29 17:14 UTC, padenot commented
@uberjay this should be available tomorrow in [Nightly](https://www.mozilla.org/fr/firefox/channel/desktop/#nightly). This installs alongside a regular Firefox fine without touching your main profile if it's just for testing (not sure how familiar you are with nightly).

General availability in Firefox release is going to be in Firefox 128, July 8th this year.

2024-05-31 01:15 UTC, uberjay commented
Fantastic, the nighty build I just tried plays using the correct channels!!! Thank you all so much, it's greatly appreciated! ❤️