Do not send extra channels for aggregate devices.
mozilla/cubeb-coreaudio-rs pull request #243
Opened 2024-11-13 21:50 UTC by mutexlox-signal

We drop the **first** several channels if there are extras (e.g. for aggregate devices) After f8df86f753d81c3ef2e8a6661b11ed65af579919, this is often incorrect
(because the first device is the input device), and also is inefficient.

So, only request the channels we're planning to use.

2024-11-13 21:50 UTC, mutexlox-signal commented
cc @Pehrsons , who I've been working with on this. You may want to do more extensive testing here; I've only tested one combination of input/output devices.

2024-11-13 21:57 UTC, mutexlox-signal commented
I believe the test failures are the same as on ToT, but I'm not sure if there are any new problems here.

2024-11-14 07:08 UTC, Pehrsons requested changes

2024-11-14 07:08 UTC, Pehrsons commented on src/backend/mod.rs
> -                p.channels = input_hw_desc.mChannelsPerFrame;
`p.channels` will now be what's requested for the cubeb input stream. But it needs to be the number of hw channels of the requested input device.

2024-11-14 07:08 UTC, Pehrsons commented on src/backend/mod.rs
>              // channels to the audio callback.
we should update these comments

2024-11-18 22:27 UTC, mutexlox-signal commented on src/backend/mod.rs
>              // channels to the audio callback.
Done.

2024-11-18 22:28 UTC, mutexlox-signal commented on src/backend/mod.rs
> -                p.channels = input_hw_desc.mChannelsPerFrame;
Done, thanks for catching this!

2024-12-03 08:05 UTC, Pehrsons approved these changes
Thanks, and sorry for the late review!
LGTM with some work on the comment.

2024-12-03 08:05 UTC, Pehrsons commented on src/backend/mod.rs
> -            // channels will be put in the beginning of the raw data given by the input callback.
Please keep this comment, but update it to make it accurate: the "our aggregate device settings" refers to the input device coming after the output device, for instance. Rather explain that the input device is set first on the aggregate device, so we only need to request those channels and CoreAudio will drop the rest automatically.

2025-03-07 16:23 UTC, mutexlox-signal commented on src/backend/mod.rs
> -            // channels will be put in the beginning of the raw data given by the input callback.
Sorry for the delay; I lost track of this and have now forgotten all context. Can you please suggest a specific phrasing, and I can update the PR?

2025-03-25 08:13 UTC, Pehrsons commented on src/backend/mod.rs
> -            // channels will be put in the beginning of the raw data given by the input callback.
Perhaps
```
Notice: when we are using aggregate device, input_hw_desc.mChannelsPerFrame is the
total of all the input channel count of the devices added in the aggregate device.
Because we set the input device first on the aggregate device, the input device's
input channels will also be first among all the aggregate device's channels, when
accessed in the input callback. By requesting only the input device's channels here,
any other input channels, i.e. from the output device, will be truncated away.
```

2025-03-28 19:47 UTC, mutexlox-signal commented on src/backend/mod.rs
> -            // channels will be put in the beginning of the raw data given by the input callback.
Thanks! Done.

2025-03-31 13:14 UTC, Pehrsons approved these changes

2025-03-31 13:14 UTC, merged