Rework threading model
mozilla/cubeb-coreaudio-rs pull request #55
Opened 2020-02-28 19:53 UTC by ChunMinChang

The change made here can address #28, and make sure that no stream task can be executed after the stream is destroyed, which should avoid the potential data race.

The patch creates a struct `Queue` wrapping `dispatch_queue_t`, which will retain and release the reference count of `dispatch_queue_t` when it's created/cloned, or destroyed. By creating the task queue in each stream, the stream's task that don't need to share the common data among all streams can be executed in each stream's own task queue. This change also brings another benefit: now we can know what task can be canceled. All the tasks appended after the stream-destroy task should be canceled.

2020-02-28 19:54 UTC, ChunMinChang commented
result on tryserver: https://treeherder.mozilla.org/#/jobs?repo=try&revision=f68714a4cf88731e50fc9278d0d6ad78647bf98c&selectedJob=291020567

2020-03-12 12:06 UTC, padenot requested changes
We need this less generic, we don't need it.

2020-03-12 12:06 UTC, padenot commented on coreaudio-sys-utils/src/dispatch.rs
> +#[derive(Debug)]
Do we need the `derive(Debug)` here? I seem to recall there was an issue with code size.

2020-03-12 12:06 UTC, padenot commented on coreaudio-sys-utils/src/dispatch.rs
> +fn create_dispatch_queue(label: &str, queue_attr: dispatch_queue_attr_t) -> dispatch_queue_t {
Have you thought about inlining all of those in the queue itself?

2020-03-12 12:06 UTC, padenot commented on coreaudio-sys-utils/src/dispatch.rs
> +    unsafe {
It would be less unsafe if you had everything in the same class.

2020-03-12 12:06 UTC, padenot commented on coreaudio-sys-utils/src/dispatch.rs
> +fn release_dispatch_queue(queue: dispatch_queue_t) {
Would be best to have a refcount class here with a drop, etc., to ensure release and retain are balanced.

2020-03-12 12:06 UTC, padenot commented on coreaudio-sys-utils/src/dispatch.rs
> +fn set_dispatch_context<T>(queue: dispatch_queue_t, context: Box<T>) {
I don't see the purpose of having two layers here really (functions + struct). Wouldn't it be better with everything inlined, and no premature generalization? You only need this for bool.

2020-03-12 12:06 UTC, padenot commented on coreaudio-sys-utils/src/dispatch.rs
> +        self.set_context(Box::new(AtomicBool::new(false)));
This should be done in the ctor, right? Then you can remove the API for context management.

2020-03-12 15:40 UTC, ChunMinChang commented on coreaudio-sys-utils/src/dispatch.rs
> +#[derive(Debug)]
Yes. `#[derive(Debug)]` is applied in `AudioUnitStream` and `AudioUnitContext` as well. As `Queue` is a member of those _strcut_ implementing `Debug` trait, `Queue` need to implement the `Debug` trait as well. Otherwise, there will be an error like:
```
`Queue` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
```

2020-03-12 15:49 UTC, ChunMinChang commented on coreaudio-sys-utils/src/dispatch.rs
> +fn set_dispatch_context<T>(queue: dispatch_queue_t, context: Box<T>) {
The main purpose to split them is to make them look clearer. I can merge those functions into the struct and see how it goes

2020-03-16 20:40 UTC, ChunMinChang commented
Try results with new patches: https://treeherder.mozilla.org/#/jobs?repo=try&selectedJob=293110963&revision=a1e4f7ac0f6103fe2e1dab2b4fd1522814952b2e

2020-03-19 14:59 UTC, padenot approved these changes

2020-03-19 14:59 UTC, padenot commented on coreaudio-sys-utils/src/dispatch.rs
> +#[derive(Debug)]
Maybe it's best to remove those as well. I thought we had a policy about that, I think on dev-platform?

2020-03-19 14:59 UTC, padenot commented on coreaudio-sys-utils/src/dispatch.rs
> +        // TODO: This is incredibly unsafe. Find another way to retain the queue.
Can you write why it is unsafe in this comment so it's clearer what you mean?

2020-03-19 16:28 UTC, ChunMinChang commented on coreaudio-sys-utils/src/dispatch.rs
> +#[derive(Debug)]
I'll open a followup PR to remove `#[derive(Debug)]` to avoid adding debug implementation stuff into the Firefox release version.

2020-03-19 16:32 UTC, ChunMinChang commented on coreaudio-sys-utils/src/dispatch.rs
> +        // TODO: This is incredibly unsafe. Find another way to retain the queue.
The comment is around calling `transmute` directly. I'll revise the comments.

2020-03-19 18:04 UTC, merged