Try using the model id as group id.
mozilla/cubeb-coreaudio-rs pull request #64
Opened 2020-03-24 19:25 UTC by padenot

It works for the all the external devices that I have, but not for the
built-in mic/speakers and the trrs plug of the macbook. I wonder if we could hardcode those.

2020-03-24 19:51 UTC, ChunMinChang reviewed
LGTM, but I think this won't pass the test since we have a check for `info.group_id == info.device_id`

https://github.com/ChunMinChang/cubeb-coreaudio-rs/blob/3860bb3f957b3be1d56a01f9e73d5d32e463eda0/src/backend/tests/api.rs#L1397

2020-03-24 19:51 UTC, ChunMinChang commented on src/backend/device_property.rs
> +    let address = get_property_address(Property::DeviceManufacturer, devtype);
`get_property_address(Property::ModelUID, devtype)`

2020-03-24 20:06 UTC, ChunMinChang commented
And we need to retake the leaked `dev_info.group_id` in `destroy_cubeb_device_info`

https://github.com/ChunMinChang/cubeb-coreaudio-rs/blob/3860bb3f957b3be1d56a01f9e73d5d32e463eda0/src/backend/mod.rs#L1636

2020-03-24 20:09 UTC, ChunMinChang commented on src/backend/mod.rs
> +            let _ = CString::from_raw(device.group_id as *mut _);
It's better to change it to
```rust
if !device.group_id.is_null() {
    let _ = CString::from_raw(device.group_id as *mut _);
    device.group_id = ptr::null();
}
```

2020-03-24 20:16 UTC, padenot commented on src/backend/mod.rs
> +            let _ = CString::from_raw(device.group_id as *mut _);
Is that only needed for the group id you think ?

2020-03-24 20:16 UTC, ChunMinChang commented on src/backend/mod.rs
> +            let _ = CString::from_raw(device.group_id as *mut _);
And we need to change here as well:

https://github.com/ChunMinChang/cubeb-coreaudio-rs/blob/3860bb3f957b3be1d56a01f9e73d5d32e463eda0/src/backend/tests/api.rs#L1497-L1499

Otherwise the `device.device_id` will be freed twice by 
```rust
let _ = CString::from_raw(device.device_id as *mut _);
```
and then
```rust
let _ = CString::from_raw(device.group_id as *mut _);
```

2020-03-24 20:18 UTC, padenot commented on src/backend/mod.rs
> +            let _ = CString::from_raw(device.group_id as *mut _);
But they are different strings now?

2020-03-24 20:19 UTC, padenot commented on src/backend/mod.rs
> +            let _ = CString::from_raw(device.group_id as *mut _);
ah I see this is the test

2020-03-24 20:19 UTC, ChunMinChang commented on src/backend/mod.rs
> +            let _ = CString::from_raw(device.group_id as *mut _);
They will be the same pointer in `test_device_destroy`

2020-03-24 20:30 UTC, padenot commented on src/backend/mod.rs
> +            let _ = CString::from_raw(device.group_id as *mut _);
Best to fix the test for new invariants.

2020-03-24 22:06 UTC, ChunMinChang commented on src/backend/mod.rs
> +            let _ = CString::from_raw(device.group_id as *mut _);
> Best to fix the test for new invariants.

Yes

On the other hand, we can remove `test_device_destroy_with_different_device_id_and_group_id` as well. It's used to check the `group_id` is same as `device_id`.

2020-03-24 22:22 UTC, ChunMinChang requested changes
The test fails on my end (and Travis server [here](https://travis-ci.org/github/ChunMinChang/cubeb-coreaudio-rs/jobs/666508423#L396)). The following things should be fixed:

1.`test_device_destroy_with_different_device_id_and_group_id` should be removed 
2. in `destroy_cubeb_device_info`, the `group_id` should be assigned to something like

```rust
let group_id = CString::new("test:group id").unwrap();
...
device.group_id = group_id.into_raw();
```

2020-03-24 22:22 UTC, ChunMinChang commented on src/backend/mod.rs
> +            }
```rust
if !device.group_id.is_null() {
    let _ = CString::from_raw(device.group_id as *mut _);
    device.group_id = ptr::null();
}
```
should be put below
```rust
if !device.device_id.is_null() {
    ...
}
```
since `group_id` isn't relied on `device_id`anymore.

2020-03-24 22:22 UTC, ChunMinChang commented on src/backend/tests/api.rs
> -        assert_eq!(info.group_id, info.device_id);
It's better to call `assert!(!info.group_id.is_null())`. 

`check_device_info_by_device` will only be called if `create_cubeb_device_info` returns `Ok(ffi::cubeb_device_info)` so `group_id` must be pointed to some leaked `CString` (by `into_raw`).

2020-03-25 10:43 UTC, padenot commented on src/backend/mod.rs
> +            }
Yes, but is it useful to allow null pointers here? Can't we enforce that the pointer is always valid (maybe to an empty string?).

2020-03-25 10:44 UTC, padenot commented on src/backend/mod.rs
> +            }
We seem to enforce it, in the test, so I don't know why we need this check. Maybe an assert would be better to document the invariant.

2020-03-25 14:28 UTC, ChunMinChang commented on src/backend/tests/api.rs
> +    device.group_id = device.device_id.clone();
If the `device.device_id` is `0xfeedfade`, then `device.group_id` is also `0xfeedfade`. Then both
`let _ = CString::from_raw(device.device_id as *mut _)` and `let _ = CString::from_raw(device.group_id as *mut _)` will be called. As a result, the `0xfeedfade` will be released twice.

2020-03-25 14:28 UTC, ChunMinChang commented on src/backend/mod.rs
> +            }
Agree. Could you replace those `if` to `assert`?

2020-03-25 22:46 UTC, ChunMinChang approved these changes

2020-03-25 22:46 UTC, merged