Test get device model uid
mozilla/cubeb-coreaudio-rs pull request #69
Opened 2020-03-27 22:35 UTC by ChunMinChang

I find my _AirPods_ will return an error when querying `group_id` and lead `test_create_cubeb_device_info` to hit an assertion. Skip checking `group_id` for now since it can be `nullptr`. On the other hand, I revise tests for `device_property` a bit. They will be used to get the device information from the hardware, or return an error if querying fails.

2020-03-31 14:34 UTC, padenot commented
I'd rather have a good group id here. We can special case airpods, we are already special-casing them elsewhere. We should also special case built-in speakers and mic, and built-in trrs plug, but this can be done in another patch.

2020-03-31 21:41 UTC, ChunMinChang commented
> I'd rather have a good group id here. We can special case airpods, we are already special-casing them elsewhere. We should also special case built-in speakers and mic, and built-in trrs plug, but this can be done in another patch.

Now, `group_id` of *AirPod* in input side and output side returns the same string. And the `group_id` of built-in speakers, mic, and built-in trrs plug are all the same (I guess they are actually on the same soundcard).

After using the global model, the *AirPods* return the [same `group_id`](https://github.com/ChunMinChang/cubeb-coreaudio-rs/pull/69/commits/8d34483f32537c3741473d92476102162dfb74b0#diff-ebe297421d02cd6119b08bad2bb71d56R1522) for both input and output scope, instead of returning a `nullptr` since failing to query `get_device_model_uid` in input or output scope.

For built-in speakers, mic, and built-in trrs plug, before or after these changes, they return the same `group_id`.

2020-04-01 16:16 UTC, padenot commented
> > I'd rather have a good group id here. We can special case airpods, we are already special-casing them elsewhere. We should also special case built-in speakers and mic, and built-in trrs plug, but this can be done in another patch.
> 
> Now, `group_id` of _AirPod_ in input side and output side returns the same string. And the `group_id` of built-in speakers, mic, and built-in trrs plug are all the same (I guess they are actually on the same soundcard).

This is not what I see on my computer (dump below).

> 
> After using the global model, the _AirPods_ return the [same `group_id`](https://github.com/ChunMinChang/cubeb-coreaudio-rs/pull/69/commits/8d34483f32537c3741473d92476102162dfb74b0#diff-ebe297421d02cd6119b08bad2bb71d56R1522) for both input and output scope, instead of returning a `nullptr` since failing to query `get_device_model_uid` in input or output scope.
> 
> For built-in speakers, mic, and built-in trrs plug, before or after these changes, they return the same `group_id`.

With or without this patch, this is what I have when running `test_devices` in the regular `cubeb` repo, with this backed:

```
dev: "BuiltInSpeakerDevice"
	Name:    "MacBook Pro Speakers"
	Group:   "Speaker"
	Vendor:  "Apple Inc."
	Type:    output
	State:   enabled
	Ch:      2
	Format:  S16LE S16BE F32LE F32BE (0x3030) (default: F32LE)
	Rate:    44100 - 96000 (default: 48000)
	Latency: lo 309 frames, hi 4390 frames
dev: "BuiltInHeadphoneOutputDevice" (PREFERRED)
	Name:    "External Headphones"
	Group:   "Codec Output"
	Vendor:  "Apple Inc."
	Type:    output
	State:   enabled
	Ch:      2
	Format:  S16LE S16BE F32LE F32BE (0x3030) (default: F32LE)
	Rate:    44100 - 96000 (default: 48000)
	Latency: lo 80 frames, hi 4161 frames
dev: "BuiltInMicrophoneDevice" (PREFERRED)
	Name:    "MacBook Pro Microphone"
	Group:   "Digital Mic"
	Vendor:  "Apple Inc."
	Type:    input
	State:   enabled
	Ch:      1
	Format:  S16LE S16BE F32LE F32BE (0x3030) (default: F32LE)
	Rate:    44100 - 96000 (default: 48000)
	Latency: lo 1971 frames, hi 6052 frames
```

> I'll add a test later to guarantee we always return the same `group_id` for <builtin mic, builtin speaker>, or <built-in trrs mic, built-in trrs speaker> and <AirPods mic, AirPods speaker>.

Sounds good, but we need to fix the above first. I'm running Catalina (10.15.4 (19E266)) on a MacBook Pro (15-inch, 2018), I don't know if this matters.

2020-04-01 16:18 UTC, padenot requested changes
This is not enough in the general case.

2020-04-01 16:18 UTC, padenot commented on src/backend/mod.rs
> +    match get_device_global_model_uid(devid) {
Does it work the other way? All devices you tried work with the global model uid?

2020-04-01 16:58 UTC, ChunMinChang commented
> With or without this patch, this is what I have when running `test_devices` in the regular `cubeb` repo, with this backed:
> 
> ```
> dev: "BuiltInSpeakerDevice"
> 	Name:    "MacBook Pro Speakers"
> 	Group:   "Speaker"
> 	Vendor:  "Apple Inc."
> 	Type:    output
> 	State:   enabled
> 	Ch:      2
> 	Format:  S16LE S16BE F32LE F32BE (0x3030) (default: F32LE)
> 	Rate:    44100 - 96000 (default: 48000)
> 	Latency: lo 309 frames, hi 4390 frames
> dev: "BuiltInHeadphoneOutputDevice" (PREFERRED)
> 	Name:    "External Headphones"
> 	Group:   "Codec Output"
> 	Vendor:  "Apple Inc."
> 	Type:    output
> 	State:   enabled
> 	Ch:      2
> 	Format:  S16LE S16BE F32LE F32BE (0x3030) (default: F32LE)
> 	Rate:    44100 - 96000 (default: 48000)
> 	Latency: lo 80 frames, hi 4161 frames
> dev: "BuiltInMicrophoneDevice" (PREFERRED)
> 	Name:    "MacBook Pro Microphone"
> 	Group:   "Digital Mic"
> 	Vendor:  "Apple Inc."
> 	Type:    input
> 	State:   enabled
> 	Ch:      1
> 	Format:  S16LE S16BE F32LE F32BE (0x3030) (default: F32LE)
> 	Rate:    44100 - 96000 (default: 48000)
> 	Latency: lo 1971 frames, hi 6052 frames
> ```


> I'm running Catalina (10.15.4 (19E266)) on a MacBook Pro (15-inch, 2018), I don't know if this matters.

Probably. I am on MacBook Pro (15-inch, 2017). The built-in speaker is
```
dev: "AppleHDAEngineOutput:1F,3,0,1,1:0"
	Name:    "Internal Speakers"
	Group:   "AppleHDA:57"
	Vendor:  "Apple Inc."
	Type:    output
	State:   enabled
	Ch:      2
	Format:  S16LE S16BE F32LE F32BE (0x3030) (default: F32LE)
	Rate:    44100 - 96000 (default: 44100)
	Latency: lo 342 frames, hi 4424 frames
```

and the microphone is: 
```
dev: "AppleHDAEngineInput:1F,3,0,1,0:1" (PREFERRED)
	Name:    "Internal Microphone"
	Group:   "AppleHDA:57"
	Vendor:  "Apple Inc."
	Type:    input
	State:   enabled
	Ch:      2
	Format:  S16LE S16BE F32LE F32BE (0x3030) (default: F32LE)
	Rate:    44100 - 96000 (default: 44100)
	Latency: lo 23 frames, hi 4105 frames
```

It seems we really need to generate a custom `group_id` for the builtin devices.

2020-04-01 17:16 UTC, ChunMinChang commented on src/backend/mod.rs
> +    match get_device_global_model_uid(devid) {
> All devices you tried work with the global model uid

Sadly I only have mbp for now. My other devices(StarTech 7.1 USB, Plantronic .Audio 628, a microphone-only USB device) are left in office.

2020-04-01 17:43 UTC, padenot commented
> but your `"BuiltInSpeakerDevice"` doesn't be replaced even you plug a TRRS
> 
> > dev: "BuiltInSpeakerDevice"
> > Name:    "MacBook Pro Speakers"
> > Group:   "Speaker"
> > Vendor:  "Apple Inc."
> > Type:    output
> > State:   enabled
> > Ch:      2
> > Format:  S16LE S16BE F32LE F32BE (0x3030) (default: F32LE)
> > Rate:    44100 - 96000 (default: 48000)
> > Latency: lo 309 frames, hi 4390 frames
> 
> Is that true?
> 
> It seems we really need to generate a custom `group_id` for the builtin devices.

Yes, it switches the default automatically when I plug something in the TRRS socket, but I can manually select the other, and for example have the speakers playing something and the headphones playing something else.

I'll agree we'll have to unfortunately handle everything, and have hard-coded strings, for when we find the case that can be reproduced on my machine.

2020-04-03 01:39 UTC, ChunMinChang commented on src/backend/mod.rs
> +) -> std::result::Result<StringRef, OSStatus> {
I think it can return `Result<CString, OSStatus>` so `StringRef::from_str` can be removed.

2020-04-03 01:39 UTC, ChunMinChang commented on src/backend/tests/api.rs
> +fn test_get_device_group_id() {
I'll loop all the devices to find the builtin-one to check in following commits.

2020-04-03 12:10 UTC, padenot approved these changes
👍. This should help quite a lot.

2020-04-03 19:51 UTC, merged